### PR TITLE
Integrate MaruSettings to system

### PR DESCRIPTION
**Pull request by utzcoz**
1. Add packages directory to `.gitignore`.
2. Include packages/apps `Android.mk`.
3. Add `MaruSettings` to product package list.
4. Add privapp permissions for `MaruSettings`.

It needs https://github.com/maruos/android_platform_frameworks_base/pull/8 to be merged.
@pdsouza , @pintaf could you help to review it? Thanks.

### CODE REVIEW

**Comment by pdsouza** [comment]
Just an update @utzcoz: I am fixing some issues on hammerhead's kernel that is preventing me from starting containers properly. Once I fix that I will be able to test these PRs. Thanks for your patience!

**Comment by pdsouza** [comment]
> Just an update @utzcoz: I am fixing some issues on hammerhead's kernel that is preventing me from starting containers properly. Once I fix that I will be able to test these PRs. Thanks for your patience!

I finally fixed hammerhead's kernel issue and I can start buster containers now! I will test out this patch and the display patches soon on hammerhead.

**Comment by utzcoz** [comment]
@pdsouza is there any update for it?

**Comment by pdsouza** [comment]
@utzcoz Sorry for the delay! Pulling it and building now.

**Comment by pdsouza** [comment]
@utzcoz Built and everything works! Incredible work man! It is great to see Desktop Settings working without modifying the Settings app! We should be able to remove it from our manifest now.

**Review by pdsouza — APPROVED** [review]
LGTM

**Pull request merged**
